{
    "metadata": {
        "kernelspec": {
            "name": "python3",
            "display_name": "Python 3 (ipykernel)",
            "language": "python"
        },
        "language_info": {
            "name": "python",
            "version": "3.8.10",
            "mimetype": "text/x-python",
            "codemirror_mode": {
                "name": "ipython",
                "version": 3
            },
            "pygments_lexer": "ipython3",
            "nbconvert_exporter": "python",
            "file_extension": ".py"
        }
    },
    "nbformat_minor": 2,
    "nbformat": 4,
    "cells": [
        {
            "cell_type": "markdown",
            "source": [
                "# 100 level\n"
            ],
            "metadata": {
                "azdata_cell_guid": "569c5002-adfb-4087-9797-4a0f168c0b35"
            }
        },
        {
            "cell_type": "code",
            "source": [
                "#Marine Engineering 200 Level, Python for ECP 281 Class.\n",
                "#Created by:Marine Engineering 200 Level University of Benin\n",
                "\n",
                "#Display the Welcome Message\n",
                "print(\"Welcome to the CGPA Calculator!\\nCreated by Marine Engineering 200 Level Students University of Benin\")\n",
                "\n",
                "#Display the Instruction\n",
                "print(\"This is a Program to calculate the CGPA of Marine Engineering Students\")\n",
                "print(\"For Grade points A=5, B=4, C=3, D=2, E=1, F=0\")\n",
                "\n",
                "#Ask user to enter Grade Points of all courses taken in 1st semester 100 level\n",
                "CHM111_GP=int(input(\"Please enter Grade Point ...CHM111:\"))\n",
                "CHM113_GP=int(input(\"Please enter Grade Point ...CHM113:\"))\n",
                "GST111_GP=int(input(\"Please enter Grade Point ...GST111:\"))\n",
                "GST112_GP=int(input(\"Please enter Grade Point ...GST112:\"))\n",
                "MTH110_GP=int(input(\"Please enter Grade Point ...MTH110:\"))\n",
                "MTH112_GP=int(input(\"Please enter Grade Point ...MTH112:\"))\n",
                "PHY111_GP=int(input(\"Please enter Grade Point ...PHY111:\"))\n",
                "PHY113_GP=int(input(\"Please enter Grade Point ...PHY113:\"))\n",
                "\n",
                "\n",
                "#Calculate Total Grade Points\n",
                "TGP1=CHM111_GP + CHM113_GP + GST111_GP + GST112_GP + MTH110_GP + MTH112_GP + PHY111_GP + PHY113_GP\n",
                "\n",
                "#Prompt user to Input Credit Units\n",
                "print(\"Please Input Credit Unit\")\n",
                "\n",
                "#Ask user to enter Credit Units of all courses taken in 1st semester 100 Level\n",
                "CHM111=int(input(\"Please enter Credit Unit ...CHM111:\"))\n",
                "CHM113=int(input(\"Please enter Credit Unit ...CHM113:\"))\n",
                "GST111=int(input(\"Please enter Credit Unit ...GST111:\"))\n",
                "GST112=int(input(\"Please enter Credit Unit ...GST112:\"))\n",
                "MTH110=int(input(\"Please enter Credit Unit ...MTH110:\"))\n",
                "MTH112=int(input(\"Please enter Credit Unit ...MTH112:\"))\n",
                "PHY111=int(input(\"Please enter Credit Unit ...PHY111:\"))\n",
                "PHY113=int(input(\"Please enter Credit Unit ...PHY113:\"))\n",
                "\n",
                "\n",
                "\n",
                "#Calculate Total Credit Unit\n",
                "TCU1=CHM111 + CHM113 + GST111 + GST112 + MTH110 + MTH112 + PHY111 + PHY113\n",
                "\n",
                "print(\"Your Total Credit Unit is:\",TCU1)\n",
                "\n",
                "#Calculate GPA of 1st semester\n",
                "GPA1=(CHM111_GP*CHM111) + (CHM113_GP*CHM113) + (GST111_GP*GST111) + (GST112_GP*GST112) + (MTH110_GP*MTH110) + (MTH112_GP*MTH112) + (PHY111_GP*PHY111) + (PHY113_GP*PHY113)\n",
                "\n",
                "print(\"Your Total Grade Point is:\",GPA1)\n",
                "\n",
                "#Calculate Total Grade Point Average\n",
                "TGPA1=GPA1/TCU1\n",
                "\n",
                "#Roundup GPA to 1 decimal place\n",
                "TGPA1=round(TGPA1,1)\n",
                "\n",
                "#Display First Semester Grade Point Average\n",
                "print(\"Your 1st Semester GPA is:\",TGPA1)\n",
                "\n",
                "#Prompt the user to continue to 2nd semester\n",
                "print(\"Please enter Grade Points & Credit Units of 2nd Semester\")\n",
                "\n",
                "#Ask user to enter Grade Point of all courses taken in 2nd semester 100 Level\n",
                "CHM124_GP=int(input(\"Please enter Grade Point ...CHM124:\"))\n",
                "CHM122_GP=int(input(\"Please enter Grade Point ...CHM122:\"))\n",
                "GST121_GP=int(input(\"Please enter Grade Point ...GST121:\"))\n",
                "GST122_GP=int(input(\"Please enter Grade Point ...GST122:\"))\n",
                "GST123_GP=int(input(\"Please enter Grade Point ...GST123:\"))\n",
                "MTH123_GP=int(input(\"Please enter Grade Point ...MTH123:\"))\n",
                "MTH125_GP=int(input(\"Please enter Grade Point ...MTH125:\"))\n",
                "PHY124_GP=int(input(\"Please enter Grade Point ...PHY124:\"))\n",
                "PHY109_GP=int(input(\"Please enter Grade Point ...PHY109:\"))\n",
                "\n",
                "\n",
                "#Calculater the Total Grade Points of 2nd Semester\n",
                "TGP2= CHM124_GP + CHM122_GP + GST121_GP + GST122_GP + GST123_GP + MTH123_GP + MTH125_GP + PHY124_GP + PHY109_GP\n",
                "\n",
                "#Prompt user to input Credit Units\n",
                "print(\"Please Input Credit Units\")\n",
                "\n",
                "#Ask user to enter Credit Units of all courses taken in 2nd semester 100 Level\n",
                "CHM124=int(input(\"Please enter Credit Unit ...CHM124:\"))\n",
                "CHM122=int(input(\"Please enter Credit Unit ...CHM122:\"))\n",
                "GST121=int(input(\"Please enter Credit Unit ...GST121:\"))\n",
                "GST122=int(input(\"Please enter Credit Unit ...GST122:\"))\n",
                "GST123=int(input(\"Please enter Credit Unit ...GST123:\"))\n",
                "MTH123=int(input(\"Please enter Credit Unit ...MTH123:\"))\n",
                "MTH125=int(input(\"Please enter Credit Unit ...MTH125:\"))\n",
                "PHY124=int(input(\"Please enter Credit Unit ...PHY124:\"))\n",
                "PHY109=int(input(\"Please enter Credit Unit ...PHY109:\"))\n",
                "\n",
                "\n",
                "#Calculate the Total Credit Units\n",
                "TCU2= CHM124 + CHM122 + GST121 + GST122 + GST123 + MTH123 + MTH125 + PHY124 + PHY109\n",
                "\n",
                "print(\"Your Total Credit Unit is:\",TCU2)\n",
                "\n",
                "#Calculate 2nd semester GPA\n",
                "GPA2=  (CHM124_GP*CHM124) + (CHM122_GP*CHM122) + (GST121_GP*GST121) + (GST122_GP*GST122) + (GST123_GP*GST123) + (MTH123_GP*MTH123) + (MTH125_GP*MTH125) + (PHY124_GP*PHY124) + (PHY109_GP*PHY109)\n",
                "print(\"Your Total Grade Point is:\",GPA2)\n",
                "\n",
                "#Calculate the Total Grade Point Average of 2nd semester.\n",
                "TGPA2=GPA2/TCU2\n",
                "\n",
                "TGPA2=round(TGPA2,1)\n",
                "\n",
                "#Display Second Semester Grade Point Average\n",
                "print(\"Your 2nd Semester GPA is:\",TGPA2)\n",
                "\n",
                "#Calculate Cumulative Grade Point Avetage.\n",
                "CGPA=(TGPA1+TGPA2)/2\n",
                "\n",
                "#Round up to 1 decimal place\n",
                "CGPA=round(CGPA,1)\n",
                "\n",
                "#Diplay the Cumulative Grade Point Average\n",
                "print(\"Your CGPA is:\",CGPA)\n",
                "\n",
                "#Assign Class of Degree\n",
                "if((CGPA>=4.50) and (CGPA<=5.00)):\n",
                "    print(\"You have;\",\"FIRST CLASS\")\n",
                "elif((CGPA>=3.50) and (CGPA<=4.49)):\n",
                "    print(\"You have;\",\"SECOND CLASS UPPER\")\n",
                "elif((CGPA>=2.50) and (CGPA<=3.49)):\n",
                "    print(\"You have;\",\"SECOND CLASS LOWER\")\n",
                "elif((CGPA>=2.50) and (CGPA<=3.49)):\n",
                "    print(\"You have;\",\"THIRD CLASS\")\n",
                "elif((CGPA>=1.00) and (CGPA<=1.49)):\n",
                "    print(\"You have;\",\"PASS\")\n",
                "elif((CGPA>=0.00) and (CGPA<=0.99)):\n",
                "    print(\"You have;\",\"FAIL\")\n",
                "else:\n",
                "    print(\"Grade Unknown\")"
            ],
            "metadata": {
                "azdata_cell_guid": "89f1b70d-3245-42ae-a920-133897950388",
                "language": "python"
            },
            "outputs": [
                {
                    "output_type": "stream",
                    "name": "stdout",
                    "text": "Welcome to the CGPA Calculator!\nCreated by Marine Engineering 200 Level Students University of Benin\nThis is a Program to calculate the CGPA of all Courses in 2 Semesters\nFor Grade points A=5, B=4, C=3, D=2, E=1, F=0\nPlease enter Grade Point ...CHM111:5\nPlease enter Grade Point ...CHM113:5\nPlease enter Grade Point ...GST111:5\nPlease enter Grade Point ...GST112:5\nPlease enter Grade Point ...MTH110:5\nPlease enter Grade Point ...MTH112:5\nPlease enter Grade Point ...PHY111:5\nPlease enter Grade Point ...PHY113:5\nPlease Input Credit Unit\nPlease enter Credit Unit ...CHM111:3\nPlease enter Credit Unit ...CHM113:3\nPlease enter Credit Unit ...GST111:2\nPlease enter Credit Unit ...GST112:2\nPlease enter Credit Unit ...MTH110:3\nPlease enter Credit Unit ...MTH112:3\nPlease enter Credit Unit ...PHY111:3\nPlease enter Credit Unit ...PHY113:3\nYour Total Credit Unit is: 22\nYour Total Grade Point is: 110\nYour 1st Semester GPA is: 5.0\nPlease enter Grade Points & Credit Units of 2nd Semester\nPlease enter Grade Point ...CHM124:4\nPlease enter Grade Point ...CHM122:4\nPlease enter Grade Point ...GST121:4\nPlease enter Grade Point ...GST122:4\nPlease enter Grade Point ...GST123:4\nPlease enter Grade Point ...MTH123:4\nPlease enter Grade Point ...MTH125:4\nPlease enter Grade Point ...PHY124:4\nPlease enter Grade Point ...PHY109:4\nPlease Input Credit Units\nPlease enter Credit Unit ...CHM124:3\nPlease enter Credit Unit ...CHM122:3\nPlease enter Credit Unit ...GST121:2\nPlease enter Credit Unit ...GST122:2\nPlease enter Credit Unit ...GST123:2\nPlease enter Credit Unit ...MTH123:3\nPlease enter Credit Unit ...MTH125:3\nPlease enter Credit Unit ...PHY124:4\nPlease enter Credit Unit ...PHY109:2\nYour Total Credit Unit is: 24\nYour Total Grade Point is: 96\nYour 2nd Semester GPA is: 4.0\nYour CGPA is: 4.5\nYou have; FIRST CLASS\n"
                }
            ],
            "execution_count": 1
        },
        {
            "cell_type": "markdown",
            "source": [
                "# 200 LEVEL\n"
            ],
            "metadata": {
                "azdata_cell_guid": "f82789d5-dfdb-4709-85cd-4dfdcd20cc83"
            }
        },
        {
            "cell_type": "code",
            "source": [
                "#Marine Engineering 200 Level, Python for ECP 281 Class.\n",
                "#Created by:Marine Engineering 200 Level University of Benin\n",
                "\n",
                "#Display the Welcome Message\n",
                "print(\"Welcome to the CGPA Calculator!\\nCreated by Marine Engineering 200 Level Students University of Benin\")\n",
                "\n",
                "#Display the Instruction\n",
                "print(\"This is a Program to calculate the CGPA of Marine Engineering Students\")\n",
                "print(\"For Grade points A=5, B=4, C=3, D=2, E=1, F=0\")\n",
                "\n",
                "#Ask user to enter Grade Points of all courses taken in 1st semester 200 Level\n",
                "CVE211_GP=int(input(\"Please enter Grade Point ...CVE211:\"))\n",
                "ECP281_GP=int(input(\"Please enter Grade Point ...ECP281:\"))\n",
                "EEE211_GP=int(input(\"Please enter Grade Point ...EEE211:\"))\n",
                "ELA201_GP=int(input(\"Please enter Grade Point ...ELA201:\"))\n",
                "EMA281_GP=int(input(\"Please enter Grade Point ...EMA281:\"))\n",
                "ENS211_GP=int(input(\"Please enter Grade Point ...ENS211:\"))\n",
                "MEE211_GP=int(input(\"Please enter Grade Point ...MEE211:\"))\n",
                "MEE221_GP=int(input(\"Please enter Grade Point ...MEE221:\"))\n",
                "PRE211_GP=int(input(\"Please enter Grade Point ...PRE211:\"))\n",
                "\n",
                "#Calculate Total Grade Points\n",
                "TGP1=CVE211_GP + ECP281_GP + EEE211_GP + ELA201_GP + EMA281_GP + ENS211_GP + MEE211_GP + MEE221_GP + PRE211_GP\n",
                "\n",
                "#Prompt user to Input Credit Units\n",
                "print(\"Please Input Credit Unit\")\n",
                "\n",
                "#Ask user to enter Credit Units of all courses taken in 1st semester 200 Level\n",
                "CVE211=int(input(\"Please enter Credit Unit ...CVE211:\"))\n",
                "ECP281=int(input(\"Please enter Credit Unit ...ECP281:\"))\n",
                "EEE211=int(input(\"Please enter Credit Unit ...EEE211:\"))\n",
                "ELA201=int(input(\"Please enter Credit Unit ...ELA201:\"))\n",
                "EMA281=int(input(\"Please enter Credit Unit ...EMA281:\"))\n",
                "ENS211=int(input(\"Please enter Credit Unit ...ENS211:\"))\n",
                "MEE211=int(input(\"Please enter Credit Unit ...MEE211:\"))\n",
                "MEE221=int(input(\"Please enter Credit Unit ...MEE221:\"))\n",
                "PRE211=int(input(\"Please enter Credit Unit ...PRE211:\"))\n",
                "\n",
                "\n",
                "#Calculate Total Credit Unit\n",
                "TCU1=CVE211 + ECP281 + EEE211 + ELA201 + EMA281 + ENS211 + MEE211 + MEE221 + PRE211\n",
                "\n",
                "print(\"Your Total Credit Unit is:\",TCU1)\n",
                "\n",
                "#Calculate GPA of 1st semester\n",
                "GPA1=(CVE211_GP*CVE211) + (ECP281_GP*ECP281) + (EEE211_GP*EEE211) + (ELA201_GP*ELA201) + (EMA281_GP*EMA281) + (ENS211_GP*ENS211) + (MEE211_GP*MEE211) + (MEE221_GP*MEE221) + (PRE211_GP*PRE211)\n",
                "\n",
                "print(\"Your Total Grade Point is:\",GPA1)\n",
                "\n",
                "#Calculate Total Grade Point Average\n",
                "TGPA3=GPA1/TCU1\n",
                "\n",
                "#Roundup GPA to 1 decimal place\n",
                "TGPA3=round(TGPA1,1)\n",
                "\n",
                "#Display First Semester Grade Point Average\n",
                "print(\"Your 1st Semester GPA is:\",TGPA1)\n",
                "\n",
                "#Prompt the user to continue to 2nd semester\n",
                "print(\"Please enter Grade Points & Credit Units of 2nd Semester\")\n",
                "\n",
                "#Ask user to enter Grade Point of all courses taken in 2nd semester 200 Level\n",
                "CHE222_GP=int(input(\"Please enter Grade Point ...CHE222:\"))\n",
                "EEE212_GP=int(input(\"Please enter Grade Point ...EEE212:\"))\n",
                "ELA202_GP=int(input(\"Please enter Grade Point ...ELA202:\"))\n",
                "EMA282_GP=int(input(\"Please enter Grade Point ...EMA282:\"))\n",
                "MEE212_GP=int(input(\"Please enter Grade Point ...MEE212:\"))\n",
                "MEE222_GP=int(input(\"Please enter Grade Point ...MEE222:\"))\n",
                "MRE212_GP=int(input(\"Please enter Grade Point ...MRE212:\"))\n",
                "PRE212_GP=int(input(\"Please enter Grade Point ...PRE212:\"))\n",
                "\n",
                "\n",
                "#Calculater the Total Grade Points of 2nd Semester\n",
                "TGP2= CHE222_GP + EEE212_GP + ELA202_GP + EMA282_GP + MEE212_GP + MEE222_GP + MRE212_GP + PRE212_GP\n",
                "\n",
                "#Prompt user to input Credit Units\n",
                "print(\"Please Input Credit Units\")\n",
                "\n",
                "#Ask user to enter Credit Units of all courses taken in 2nd semester 200 Level\n",
                "CHE222=int(input(\"Please enter Credit Unit ...CHE222:\"))\n",
                "EEE212=int(input(\"Please enter Credit Unit ...EEE212:\"))\n",
                "ELA202=int(input(\"Please enter Credit Unit ...ELA202:\"))\n",
                "EMA282=int(input(\"Please enter Credit Unit ...EMA282:\"))\n",
                "MEE212=int(input(\"Please enter Credit Unit ...MEE212:\"))\n",
                "MEE222=int(input(\"Please enter Credit Unit ...MEE222:\"))\n",
                "MRE212=int(input(\"Please enter Credit Unit ...MRE212:\"))\n",
                "PRE212=int(input(\"Please enter Credit Unit ...PRE212:\"))\n",
                "\n",
                "#Calculate the Total Credit Units\n",
                "TCU2= CHE222 + EEE212 + ELA202 + EMA282 + MEE212 + MEE222 + MRE212 + PRE212\n",
                "\n",
                "print(\"Your Total Credit Unit is:\",TCU2)\n",
                "\n",
                "#Calculate 2nd semester GPA\n",
                "GPA2=(CHE222_GP*CHE222) + (EEE212_GP*EEE212) + (ELA202_GP*ELA202) + (EMA282_GP*EMA282) + (MEE212_GP*MEE212) + (MEE222_GP*MEE222) + (MRE212_GP*MRE212) + (PRE212_GP*PRE212)\n",
                "\n",
                "print(\"Your Total Grade Point is:\",GPA2)\n",
                "\n",
                "#Calculate the Total Grade Point Average of 2nd semester.\n",
                "TGPA4=GPA2/TCU2\n",
                "\n",
                "TGPA4=round(TGPA4,1)\n",
                "\n",
                "#Display Second Semester Grade Point Average\n",
                "print(\"Your 2nd Semester GPA is:\",TGPA4)\n",
                "\n",
                "#Calculate Cumulative Grade Point Avetage.\n",
                "CGPA=((TGPA1+TGPA2)/2 + (TGPA3+TGPA4)/2) / 2\n",
                "\n",
                "#Round up to 1 decimal place\n",
                "CGPA=round(CGPA,1)\n",
                "\n",
                "#Diplay the Cumulative Grade Point Average\n",
                "print(\"Your CGPA is:\",CGPA)\n",
                "\n",
                "#Assign Class of Degree\n",
                "if((CGPA>=4.50) and (CGPA<=5.00)):\n",
                "    print(\"You have;\",\"FIRST CLASS\")\n",
                "elif((CGPA>=3.50) and (CGPA<=4.49)):\n",
                "    print(\"You have;\",\"SECOND CLASS UPPER\")\n",
                "elif((CGPA>=2.50) and (CGPA<=3.49)):\n",
                "    print(\"You have;\",\"SECOND CLASS LOWER\")\n",
                "elif((CGPA>=2.50) and (CGPA<=3.49)):\n",
                "    print(\"You have;\",\"THIRD CLASS\")\n",
                "elif((CGPA>=1.00) and (CGPA<=1.49)):\n",
                "    print(\"You have;\",\"PASS\")\n",
                "elif((CGPA>=0.00) and (CGPA<=0.99)):\n",
                "    print(\"You have;\",\"FAIL\")\n",
                "else:\n",
                "    print(\"Grade Unknown\")"
            ],
            "metadata": {
                "azdata_cell_guid": "1d9fd672-c76c-4937-91ee-74da8ba65264",
                "language": "python"
            },
            "outputs": [
                {
                    "output_type": "stream",
                    "name": "stdout",
                    "text": "Welcome to the CGPA Calculator!\nCreated by Marine Engineering 200 Level Students University of Benin\nThis is a Program to calculate the CGPA of all Courses in 2 Semesters\nFor Grade points A=5, B=4, C=3, D=2, E=1, F=0\nPlease enter Grade Point ...CVE211:5\nPlease enter Grade Point ...ECP281:5\nPlease enter Grade Point ...EEE211:5\nPlease enter Grade Point ...ELA201:5\nPlease enter Grade Point ...EMA281:5\nPlease enter Grade Point ...ENS211:5\nPlease enter Grade Point ...MEE211:5\nPlease enter Grade Point ...MEE221:5\nPlease enter Grade Point ...PRE211:5\nPlease Input Credit Unit\nPlease enter Credit Unit ...CVE211:3\nPlease enter Credit Unit ...ECP281:2\nPlease enter Credit Unit ...EEE211:3\nPlease enter Credit Unit ...ELA201:2\nPlease enter Credit Unit ...EMA281:2\nPlease enter Credit Unit ...ENS211:2\nPlease enter Credit Unit ...MEE211:3\nPlease enter Credit Unit ...MEE221:3\nPlease enter Credit Unit ...PRE211:2\nYour Total Credit Unit is: 22\nYour Total Grade Point is: 110\nYour 1st Semester GPA is: 5.0\nPlease enter Grade Points & Credit Units of 2nd Semester\nPlease enter Grade Point ...CHE222:4\nPlease enter Grade Point ...EEE212:4\nPlease enter Grade Point ...ELA202:4\nPlease enter Grade Point ...EMA282:4\nPlease enter Grade Point ...MEE212:4\nPlease enter Grade Point ...MEE222:4\nPlease enter Grade Point ...MRE212:4\nPlease enter Grade Point ...PRE212:4\nPlease Input Credit Units\nPlease enter Credit Unit ...CHE222:2\nPlease enter Credit Unit ...EEE212:3\nPlease enter Credit Unit ...ELA202:2\nPlease enter Credit Unit ...EMA282:4\nPlease enter Credit Unit ...MEE212:3\nPlease enter Credit Unit ...MEE222:3\nPlease enter Credit Unit ...MRE212:2\nPlease enter Credit Unit ...PRE212:2\nYour Total Credit Unit is: 21\nYour Total Grade Point is: 84\nYour 2nd Semester GPA is: 4.0\nYour CGPA is: 4.5\nYou have; FIRST CLASS\n"
                }
            ],
            "execution_count": 3
        },
        {
            "cell_type": "markdown",
            "source": [
                "# 300 Level\n"
            ],
            "metadata": {
                "azdata_cell_guid": "5e9106b9-1323-4354-a34d-646bc9a02718"
            }
        },
        {
            "cell_type": "code",
            "source": [
                "## Marine Engineering 200 Level, Python for ECP 281 Class.\n",
                "#Created by:Marine Engineering 200 Level University of Benin\n",
                "\n",
                "#Display the Welcome Message\n",
                "print(\"Welcome to the CGPA Calculator!\\nCreated by Marine Engineering 200 Level Students University of Benin\")\n",
                "\n",
                "#Display the Instruction\n",
                "print(\"This is a Program to calculate the CGPA of all Marine Engineering Students\")\n",
                "print(\"For Grade points A=5, B=4, C=3, D=2, E=1, F=0\")\n",
                "\n",
                "#Ask user to enter Grade Points of all Courses taken in 1st semester 300 Level\n",
                "EMA381_GP=int(input(\"Please enter Grade Point ...EMA381:\"))\n",
                "MEE351_GP=int(input(\"Please enter Grade Point ...MEE351:\"))\n",
                "EEE311_GP=int(input(\"Please enter Grade Point ...EEE311:\"))\n",
                "MEE361_GP=int(input(\"Please enter Grade Point ...MEE361:\"))\n",
                "MRE310_GP=int(input(\"Please enter Grade Point ...MRE310:\"))\n",
                "PRE311_GP=int(input(\"Please enter Grade Point ...PRE311:\"))\n",
                "MRE316_GP=int(input(\"Please enter Grade Point ...MRE316:\"))\n",
                "MRE311_GP=int(input(\"Please enter Grade Point ...MRE311:\"))\n",
                "MRE317_GP=int(input(\"Please enter Grade Point ...MRE317:\"))\n",
                "ELA301_GP=int(input(\"Please enter Grade Point ...ELA301:\"))\n",
                "\n",
                "#Calculate Total Grade Points\n",
                "TGP1=EMA381_GP + MEE351_GP + EEE311_GP + MEE361_GP + MRE310_GP + PRE311_GP + MRE316_GP + MRE311_GP + MRE317_GP + ELA301_GP\n",
                "\n",
                "#Prompt user to Input Credit Units\n",
                "print(\"Please Input Credit Unit\")\n",
                "\n",
                "#Ask user to enter Credit Units of all courses taken in 1st semester 300 Level\n",
                "EMA381=int(input(\"Please enter Credit Unit ...EMA381:\"))\n",
                "MEE351=int(input(\"Please enter Credit Unit ...MEE351:\"))\n",
                "EEE311=int(input(\"Please enter Credit Unit ...EEE311:\"))\n",
                "MEE361=int(input(\"Please enter Credit Unit ...MEE361:\"))\n",
                "MRE310=int(input(\"Please enter Credit Unit ...MRE310:\"))\n",
                "PRE311=int(input(\"Please enter Credit Unit ...PRE311:\"))\n",
                "MRE316=int(input(\"Please enter Credit Unit ...MRE316:\"))\n",
                "MRE311=int(input(\"Please enter Credit Unit ...MRE311:\"))\n",
                "MRE317=int(input(\"Please enter Credit Unit ...MRE317:\"))\n",
                "ELA301=int(input(\"Please enter Credit Unit ...ELA301:\"))\n",
                "\n",
                "\n",
                "#Calculate Total Credit Unit\n",
                "TCU1=EMA381 + MEE351 + EEE311 + MEE361 + MRE310 + PRE311 + MRE316 + MRE311 + MRE317 + ELA301\n",
                "\n",
                "print(\"Your Total Credit Unit is:\",TCU1)\n",
                "\n",
                "#Calculate GPA of 1st semester\n",
                "GPA1=(EMA381_GP*EMA381) + (MEE351_GP*MEE351) + (EEE311_GP*EEE311) + (MEE361_GP*MEE361) + (MRE310_GP*MRE310) + (PRE311_GP*PRE311) + (MRE316_GP*MRE316) + (MRE311_GP*MRE311) + (MRE317_GP*MRE317) + (ELA301_GP*ELA301)\n",
                "\n",
                "print(\"Your Total Grade Point is:\",GPA1)\n",
                "\n",
                "#Calculate Total Grade Point Average\n",
                "TGPA5=GPA1/TCU1\n",
                "\n",
                "#Roundup GPA to 1 decimal place\n",
                "TGPA5=round(TGPA5,1)\n",
                "\n",
                "#Display First Semester Grade Point Average\n",
                "print(\"Your 1st Semester GPA is:\",TGPA5)\n",
                "\n",
                "#Prompt the user to continue to 2nd semester\n",
                "print(\"Please enter Grade Points & Credit Units of 2nd Semester\")\n",
                "\n",
                "#Ask user to enter Grade Point of all courses taken in 2nd semester 300 Level\n",
                "EMA382_GP=int(input(\"Please enter Grade Point ...EMA382:\"))\n",
                "MRE376_GP=int(input(\"Please enter Grade Point ...MRE376:\"))\n",
                "EEE312_GP=int(input(\"Please enter Grade Point ...EEE312:\"))\n",
                "MRE314_GP=int(input(\"Please enter Grade Point ...MRE314:\"))\n",
                "EEE316_GP=int(input(\"Please enter Grade Point ...EEE316:\"))\n",
                "EEE332_GP=int(input(\"Please enter Grade Point ...EEE332:\"))\n",
                "MRE312_GP=int(input(\"Please enter Grade Point ...MRE312:\"))\n",
                "ELA302_GP=int(input(\"Please enter Grade Point ...ELA302:\"))\n",
                "\n",
                "\n",
                "#Calculater the Total Grade Points of 2nd Semester\n",
                "TGP2= EMA382_GP + MRE376_GP + EEE312_GP + MRE314_GP + EEE316_GP + EEE332_GP + MRE312_GP + ELA302_GP\n",
                "\n",
                "#Prompt user to input Credit Units\n",
                "print(\"Please Input Credit Units\")\n",
                "\n",
                "#Ask user to enter Credit Units of all courses taken in 2nd semester 300 Level\n",
                "EMA382=int(input(\"Please enter Credit Unit ...EMA382:\"))\n",
                "MRE376=int(input(\"Please enter Credit Unit ...MRE376:\"))\n",
                "EEE312=int(input(\"Please enter Credit Unit ...EEE312:\"))\n",
                "MRE314=int(input(\"Please enter Credit Unit ...MRE314:\"))\n",
                "EEE316=int(input(\"Please enter Credit Unit ...EEE316:\"))\n",
                "EEE332=int(input(\"Please enter Credit Unit ...EEE332:\"))\n",
                "MRE312=int(input(\"Please enter Credit Unit ...MRE312:\"))\n",
                "ELA302=int(input(\"Please enter Credit Unit ...ELA302:\"))\n",
                "\n",
                "#Calculate the Total Credit Units\n",
                "TCU2=  EMA382 + MRE376 + EEE312 + MRE314 + EEE316 + EEE332 + MRE312 + ELA302\n",
                "\n",
                "print(\"Your Total Credit Unit is:\",TCU2)\n",
                "\n",
                "#Calculate 2nd semester GPA\n",
                "GPA2= (EMA382_GP*EMA382) + (MRE376_GP*MRE376) + (EEE312_GP*EEE312) + (MRE314_GP*MRE314) + (EEE316_GP*EEE316) + (EEE332_GP*EEE332) + (MRE312_GP*MRE312) + (ELA302_GP*ELA302)\n",
                "\n",
                "print(\"Your Total Grade Point is:\",GPA2)\n",
                "\n",
                "#Calculate the Total Grade Point Average of 2nd semester.\n",
                "TGPA6=GPA2/TCU2\n",
                "\n",
                "TGPA6=round(TGPA6,1)\n",
                "\n",
                "#Display Second Semester Grade Point Average\n",
                "print(\"Your 2nd Semester GPA is:\",TGPA6)\n",
                "\n",
                "#Calculate Cumulative Grade Point Avetage.\n",
                "CGPA=((TGPA1+TGPA2)/2 + (TGPA3+TGPA4)/2 + (TGPA5+TGPA6)/2) / 3\n",
                "\n",
                "#Round up to 1 decimal place\n",
                "CGPA=round(CGPA,1)\n",
                "\n",
                "#Diplay the Cumulative Grade Point Average\n",
                "print(\"Your CGPA is:\",CGPA)\n",
                "\n",
                "#Assign Class of Degree\n",
                "if((CGPA>=4.50) and (CGPA<=5.00)):\n",
                "    print(\"You have;\",\"FIRST CLASS\")\n",
                "elif((CGPA>=3.50) and (CGPA<=4.49)):\n",
                "    print(\"You have;\",\"SECOND CLASS UPPER\")\n",
                "elif((CGPA>=2.50) and (CGPA<=3.49)):\n",
                "    print(\"You have;\",\"SECOND CLASS LOWER\")\n",
                "elif((CGPA>=2.50) and (CGPA<=3.49)):\n",
                "    print(\"You have;\",\"THIRD CLASS\")\n",
                "elif((CGPA>=1.00) and (CGPA<=1.49)):\n",
                "    print(\"You have;\",\"PASS\")\n",
                "elif((CGPA>=0.00) and (CGPA<=0.99)):\n",
                "    print(\"You have;\",\"FAIL\")\n",
                "else:\n",
                "    print(\"Grade Unknown\")"
            ],
            "metadata": {
                "azdata_cell_guid": "e2105f62-f6cb-4459-88ac-c596d630767f",
                "language": "python"
            },
            "outputs": [
                {
                    "output_type": "stream",
                    "name": "stdout",
                    "text": "Welcome to the CGPA Calculator!\nCreated by Marine Engineering 200 Level Students University of Benin\nThis is a Program to calculate the CGPA of all Courses in 2 Semesters\nFor Grade points A=5, B=4, C=3, D=2, E=1, F=0\nPlease enter Grade Point ...EMA381:3\nPlease enter Grade Point ...MEE351:4\nPlease enter Grade Point ...EEE311:3\nPlease enter Grade Point ...MEE361:4\nPlease enter Grade Point ...MRE310:3\nPlease enter Grade Point ...PRE311:4\nPlease enter Grade Point ...MRE316:3\nPlease enter Grade Point ...MRE311:4\nPlease enter Grade Point ...MRE317:3\nPlease enter Grade Point ...ELA301:4\nPlease Input Credit Unit\nPlease enter Credit Unit ...EMA381:3\nPlease enter Credit Unit ...MEE351:3\nPlease enter Credit Unit ...EEE311:3\nPlease enter Credit Unit ...MEE361:3\nPlease enter Credit Unit ...MRE310:2\nPlease enter Credit Unit ...PRE311:2\nPlease enter Credit Unit ...MRE316:3\nPlease enter Credit Unit ...MRE311:2\nPlease enter Credit Unit ...MRE317:2\nPlease enter Credit Unit ...ELA301:2\nYour Total Credit Unit is: 25\nYour Total Grade Point is: 87\nYour 1st Semester GPA is: 3.5\nPlease enter Grade Points & Credit Units of 2nd Semester\nPlease enter Grade Point ...EMA382:4\nPlease enter Grade Point ...MRE376:3\nPlease enter Grade Point ...EEE312:4\nPlease enter Grade Point ...MRE314:3\nPlease enter Grade Point ...EEE316:4\nPlease enter Grade Point ...EEE332:3\nPlease enter Grade Point ...MRE312:4\nPlease enter Grade Point ...ELA302:3\nPlease Input Credit Units\nPlease enter Credit Unit ...EMA382:3\nPlease enter Credit Unit ...MRE376:3\nPlease enter Credit Unit ...EEE312:3\nPlease enter Credit Unit ...MRE314:3\nPlease enter Credit Unit ...EEE316:3\nPlease enter Credit Unit ...EEE332:3\nPlease enter Credit Unit ...MRE312:2\nPlease enter Credit Unit ...ELA302:2\nYour Total Credit Unit is: 22\nYour Total Grade Point is: 77\nYour 2nd Semester GPA is: 3.5\nYour CGPA is: 4.2\nYou have; SECOND CLASS UPPER\n"
                }
            ],
            "execution_count": 5
        },
        {
            "cell_type": "markdown",
            "source": [
                "# 400 Level "
            ],
            "metadata": {
                "azdata_cell_guid": "ab7911df-92e0-45d4-9240-b64d9468e2e3"
            }
        },
        {
            "cell_type": "code",
            "source": [
                "#Marine Engineering 200 Level, Python for ECP 281 Class.\n",
                "#Created by:Marine Engineering 200 Level University of Benin\n",
                "\n",
                "#Display the Welcome Message\n",
                "print(\"Welcome to the CGPA Calculator!\\nCreated by Marine Engineering 200 Level Students University of Benin\")\n",
                "\n",
                "#Display the Instruction\n",
                "print(\"This is a Program to calculate the CGPA of Marine Engineering Students\")\n",
                "print(\"For Grade points A=5, B=4, C=3, D=2, E=1, F=0\")\n",
                "\n",
                "#Ask user to enter Grade Points of all Courses in 1st semester 400 Level\n",
                "EMA481_GP=int(input(\"Please enter Grade Point ...EMA481:\"))\n",
                "MRE431_GP=int(input(\"Please enter Grade Point ...MRE431:\"))\n",
                "MRE411_GP=int(input(\"Please enter Grade Point ...MRE411:\"))\n",
                "MRE410_GP=int(input(\"Please enter Grade Point ...MRE410:\"))\n",
                "MRE412_GP=int(input(\"Please enter Grade Point ...MRE412:\"))\n",
                "MRE416_GP=int(input(\"Please enter Grade Point ...MRE416:\"))\n",
                "EEE453_GP=int(input(\"Please enter Grade Point ...EEE453:\"))\n",
                "ELA401_GP=int(input(\"Please enter Grade Point ...ELA401:\"))\n",
                "\n",
                "\n",
                "#Calculate Total Grade Points\n",
                "TGP1= EMA481_GP + MRE431_GP + MRE411_GP + MRE410_GP + MRE412_GP + MRE416_GP + EEE453_GP + ELA401_GP\n",
                "\n",
                "#Prompt user to Input Credit Units\n",
                "print(\"Please Input Credit Unit\")\n",
                "\n",
                "#Ask user to enter Credit Units of all courses in 1st semester 400 Level\n",
                "EMA481=int(input(\"Please enter Credit Unit ...EMA481:\"))\n",
                "MRE431=int(input(\"Please enter Credit Unit ...MRE431:\"))\n",
                "MRE411=int(input(\"Please enter Credit Unit ...MRE411:\"))\n",
                "MRE410=int(input(\"Please enter Credit Unit ...MRE410:\"))\n",
                "MRE412=int(input(\"Please enter Credit Unit ...MRE412:\"))\n",
                "MRE416=int(input(\"Please enter Credit Unit ...MRE416:\"))\n",
                "EEE453=int(input(\"Please enter Credit Unit ...EEE453:\"))\n",
                "ELA401=int(input(\"Please enter Credit Unit ...ELA401:\"))\n",
                "\n",
                "\n",
                "#Calculate Total Credit Unit\n",
                "TCU1=EMA481 + MRE431 + MRE411 + MRE410 + MRE412 + MRE416 + EEE453 + ELA401\n",
                "\n",
                "print(\"Your Total Credit Unit is:\",TCU1)\n",
                "\n",
                "#Calculate GPA of 1st semester\n",
                "GPA1= (EMA481_GP*EMA481) + (MRE431_GP*MRE431) + (MRE411_GP*MRE411) + (MRE410_GP*MRE410) + (MRE412_GP*MRE412) + (MRE416_GP*MRE416) + (EEE453_GP*EEE453) + (ELA401_GP*ELA401)\n",
                "\n",
                "print(\"Your Total Grade Point is:\",GPA1)\n",
                "\n",
                "#Calculate Total Grade Point Average\n",
                "TGPA7=GPA1/TCU1\n",
                "\n",
                "#Roundup GPA to 1 decimal place\n",
                "TGPA7=round(TGPA7,1)\n",
                "\n",
                "#Display First Semester Grade Point Average\n",
                "print(\"Your 1st Semester GPA is:\",TGPA7)\n",
                "\n",
                "#Prompt the user to continue to 2nd semester\n",
                "print(\"Please enter Grade Points & Credit Units of 2nd Semester\")\n",
                "\n",
                "#Ask user to enter Grade Point For UBITS in 2nd semester 400 Level\n",
                "UBITS_GP=int(input(\"Please enter Grade Point ...UBITS:\"))\n",
                "\n",
                "#Calculater the Total Grade Points of 2nd Semester\n",
                "TGP2= UBITS_GP\n",
                "\n",
                "#Prompt user to input Credit Units\n",
                "print(\"Please Input Credit Units\")\n",
                "\n",
                "#Ask user to enter Credit Units For UBITS in 2nd semester 400 Level\n",
                "UBITS=int(input(\"Please enter Credit Unit ...UBITS:\"))\n",
                "\n",
                "\n",
                "#Calculate the Total Credit Units\n",
                "TCU2=  UBITS\n",
                "\n",
                "print(\"Your Total Credit Unit is:\",TCU2)\n",
                "\n",
                "#Calculate 2nd semester GPA\n",
                "GPA2= (UBITS_GP*UBITS)\n",
                "\n",
                "print(\"Your Total Grade Point is:\",GPA2)\n",
                "\n",
                "#Calculate the Total Grade Point Average of 2nd semester.\n",
                "TGPA8=GPA2/TCU2\n",
                "\n",
                "TGPA8=round(TGPA8,1)\n",
                "\n",
                "#Display Second Semester Grade Point Average\n",
                "print(\"Your 2nd Semester GPA is:\",TGPA8)\n",
                "\n",
                "#Calculate Cumulative Grade Point Avetage.\n",
                "CGPA=((TGPA1+TGPA2)/2 + (TGPA3+TGPA4)/2 + (TGPA5+TGPA6)/2 + (TGPA7+TGPA8)/2) / 4\n",
                "\n",
                "#Round up to 1 decimal place\n",
                "CGPA=round(CGPA,1)\n",
                "\n",
                "#Diplay the Cumulative Grade Point Average\n",
                "print(\"Your CGPA is:\",CGPA)\n",
                "\n",
                "#Assign Class of Degree\n",
                "if((CGPA>=4.50) and (CGPA<=5.00)):\n",
                "    print(\"You have;\",\"FIRST CLASS\")\n",
                "elif((CGPA>=3.50) and (CGPA<=4.49)):\n",
                "    print(\"You have;\",\"SECOND CLASS UPPER\")\n",
                "elif((CGPA>=2.50) and (CGPA<=3.49)):\n",
                "    print(\"You have;\",\"SECOND CLASS LOWER\")\n",
                "elif((CGPA>=2.50) and (CGPA<=3.49)):\n",
                "    print(\"You have;\",\"THIRD CLASS\")\n",
                "elif((CGPA>=1.00) and (CGPA<=1.49)):\n",
                "    print(\"You have;\",\"PASS\")\n",
                "elif((CGPA>=0.00) and (CGPA<=0.99)):\n",
                "    print(\"You have;\",\"FAIL\")\n",
                "else:\n",
                "    print(\"Grade Unknown\")"
            ],
            "metadata": {
                "azdata_cell_guid": "e9d7e163-dc25-49ec-bdb4-8e4cd53a2b7b",
                "language": "python"
            },
            "outputs": [
                {
                    "output_type": "stream",
                    "name": "stdout",
                    "text": "Welcome to the CGPA Calculator!\nCreated by Marine Engineering 200 Level Students University of Benin\nThis is a Program to calculate the CGPA of all Courses in 2 Semesters\nFor Grade points A=5, B=4, C=3, D=2, E=1, F=0\nPlease enter Grade Point ...EMA481:4\nPlease enter Grade Point ...MRE431:4\nPlease enter Grade Point ...MRE411:4\nPlease enter Grade Point ...MRE410:4\nPlease enter Grade Point ...MRE412:4\nPlease enter Grade Point ...MRE416:4\nPlease enter Grade Point ...EEE453:4\nPlease enter Grade Point ...ELA401:4\nPlease Input Credit Unit\nPlease enter Credit Unit ...EMA481:3\nPlease enter Credit Unit ...MRE431:3\nPlease enter Credit Unit ...MRE411:3\nPlease enter Credit Unit ...MRE410:3\nPlease enter Credit Unit ...MRE412:3\nPlease enter Credit Unit ...MRE416:3\nPlease enter Credit Unit ...EEE453:3\nPlease enter Credit Unit ...ELA401:2\nYour Total Credit Unit is: 23\nYour Total Grade Point is: 92\nYour 1st Semester GPA is: 4.0\nPlease enter Grade Points & Credit Units of 2nd Semester\nPlease enter Grade Point ...UBITS:4\nPlease Input Credit Units\nPlease enter Credit Unit ...UBITS:6\nYour Total Credit Unit is: 6\nYour Total Grade Point is: 24\nYour 2nd Semester GPA is: 4.0\nYour CGPA is: 4.0\nYou have; SECOND CLASS UPPER\n"
                }
            ],
            "execution_count": 6
        },
        {
            "cell_type": "markdown",
            "source": [
                "# 500 Level"
            ],
            "metadata": {
                "azdata_cell_guid": "965b3f9e-cd14-4119-9bdc-6e0803fe6e35"
            }
        },
        {
            "cell_type": "code",
            "source": [
                "#Marine Engineering 200 Level, Python for ECP 281 Class.\n",
                "#Created by:Marine Engineering 200 Level University of Benin\n",
                "\n",
                "#Display the Welcome Message\n",
                "print(\"Welcome to the CGPA Calculator!\\nCreated by Marine Engineering 200 Level Students University of Benin\")\n",
                "\n",
                "#Display the Instruction\n",
                "print(\"This is a Program to calculate the CGPA of all Courses in 2 Semesters\")\n",
                "print(\"For Grade points A=5, B=4, C=3, D=2, E=1, F=0\")\n",
                "\n",
                "#Ask user to enter Grade Points ofall courses in 1st semester 500 Level\n",
                "PRE571_GP=int(input(\"Please enter Grade Point ...PRE571:\"))\n",
                "MRE591_GP=int(input(\"Please enter Grade Point ...MRE591:\"))\n",
                "MRE513_GP=int(input(\"Please enter Grade Point ...MRE513:\"))\n",
                "MRE511_GP=int(input(\"Please enter Grade Point ...MRE511:\"))\n",
                "MRE506_GP=int(input(\"Please enter Grade Point ...MRE506:\"))\n",
                "MRE508_GP=int(input(\"Please enter Grade Point ...MRE508:\"))\n",
                "MRE527_GP=int(input(\"Please enter Grade Point ...MRE527:\"))\n",
                "MRE501_GP=int(input(\"Please enter Grade Point ...MRE501:\"))\n",
                "\n",
                "\n",
                "#Calculate Total Grade Points\n",
                "TGP1=PRE571_GP + MRE591_GP + MRE513_GP + MRE511_GP + MRE506_GP + MRE508_GP + MRE527_GP + MRE501_GP\n",
                "\n",
                "#Prompt user to Input Credit Units\n",
                "print(\"Please Input Credit Unit\")\n",
                "\n",
                "#Ask user to enter Credit Units of all courses in 1st semester 500 Level\n",
                "PRE571=int(input(\"Please enter Credit Unit ...PRE571:\"))\n",
                "MRE591=int(input(\"Please enter Credit Unit ...MRE591:\"))\n",
                "MRE513=int(input(\"Please enter Credit Unit ...MRE513:\"))\n",
                "MRE511=int(input(\"Please enter Credit Unit ...MRE511:\"))\n",
                "MRE506=int(input(\"Please enter Credit Unit ...MRE506:\"))\n",
                "MRE508=int(input(\"Please enter Credit Unit ...MRE508:\"))\n",
                "MRE527=int(input(\"Please enter Credit Unit ...MRE527:\"))\n",
                "MRE501=int(input(\"Please enter Credit Unit ...MRE501:\"))\n",
                "\n",
                "#Calculate Total Credit Unit\n",
                "TCU1=PRE571 + MRE591 + MRE513 + MRE511 + MRE506 + MRE508 + MRE527 + MRE501\n",
                "\n",
                "print(\"Your Total Credit Unit is:\",TCU1)\n",
                "\n",
                "#Calculate GPA of 1st semester\n",
                "GPA1=(PRE571_GP*PRE571) + (MRE591_GP*MRE591) + (MRE513_GP*MRE513) + (MRE511_GP*MRE511) + (MRE506_GP*MRE506) + (MRE508_GP*MRE508) + (MRE527_GP*MRE527) + (MRE501_GP*MRE501)\n",
                "\n",
                "print(\"Your Total Grade Point is:\",GPA1)\n",
                "\n",
                "#Calculate Total Grade Point Average\n",
                "TGPA9=GPA1/TCU1\n",
                "\n",
                "#Roundup GPA to 1 decimal place\n",
                "TGPA9=round(TGPA9,1)\n",
                "\n",
                "#Display First Semester Grade Point Average\n",
                "print(\"Your 1st Semester GPA is:\",TGPA9)\n",
                "\n",
                "#Prompt the user to continue to 2nd semester\n",
                "print(\"Please enter Grade Points & Credit Units of 2nd Semester\")\n",
                "\n",
                "#Ask user to enter Grade Point of all course in 2nd semester 500 Level\n",
                "PRE572_GP=int(input(\"Please enter Grade Point ...PRE572:\"))\n",
                "MRE502_GP=int(input(\"Please enter Grade Point ...MRE502:\"))\n",
                "print(\"pick 5 optonal courses and input 0 as grade point for courses you did not take\")\n",
                "MRE532_GP=int(input(\"Please enter Grade Point ...MRE532:\"))\n",
                "MRE518_GP=int(input(\"Please enter Grade Point ...MRE581:\"))\n",
                "MRE517_GP=int(input(\"Please enter Grade Point ...MRE517:\"))\n",
                "MRE516_GP=int(input(\"Please enter Grade Point ...MRE516:\"))\n",
                "MRE574_GP=int(input(\"Please enter Grade Point ...MRE574:\"))\n",
                "MRE576_GP=int(input(\"Please enter Grade Point ...MRE576:\"))\n",
                "MRE545_GP=int(input(\"Please enter Grade Point ...MRE545:\"))\n",
                "MRE544_GP=int(input(\"Please enter Grade Point ...MRE544:\"))\n",
                "MRE477_GP=int(input(\"Please enter Grade Point ...MRE477:\"))\n",
                "MRE541_GP=int(input(\"Please enter Grade Point ...MRE541:\"))\n",
                "MRE578_GP=int(input(\"Please enter Grade Point ...MRE578:\"))\n",
                "\n",
                "\n",
                "#Calculater the Total Grade Points of 2nd Semester\n",
                "TGP2= PRE572_GP + MRE502_GP + MRE532_GP + MRE518_GP + MRE517_GP + MRE516_GP + MRE574_GP + MRE576_GP + MRE545_GP + MRE544_GP + MRE477_GP + MRE541_GP + MRE578_GP\n",
                "\n",
                "#Prompt user to input Credit Units\n",
                "print(\"Please Input Credit Units\")\n",
                "\n",
                "#Ask user to enter Credit Units of all courses in 2nd semester 500 Level\n",
                "PRE572=int(input(\"Please enter Credit Unit ...PRE572:\"))\n",
                "MRE502=int(input(\"Please enter Credit Unit ...MRE502:\"))\n",
                "print(\"pick 5 optonal courses and input 0 as credit unit for courses you did not take\")\n",
                "MRE532=int(input(\"Please enter Credit Unit ...MRE532:\"))\n",
                "MRE518=int(input(\"Please enter Credit Unit ...MRE581:\"))\n",
                "MRE517=int(input(\"Please enter Credit Unit ...MRE517:\"))\n",
                "MRE516=int(input(\"Please enter Credit Unit ...MRE516:\"))\n",
                "MRE574=int(input(\"Please enter Credit Unit ...MRE574:\"))\n",
                "MRE576=int(input(\"Please enter Credit Unit ...MRE576:\"))\n",
                "MRE545=int(input(\"Please enter Credit Unit ...MRE545:\"))\n",
                "MRE544=int(input(\"Please enter Credit Unit ...MRE544:\"))\n",
                "MRE477=int(input(\"Please enter Credit Unit ...MRE477:\"))\n",
                "MRE541=int(input(\"Please enter Credit Unit ...MRE541:\"))\n",
                "MRE578=int(input(\"Please enter Credit Unit ...MRE578:\"))\n",
                "\n",
                "\n",
                "#Calculate the Total Credit Units\n",
                "TCU2= PRE572 + MRE502 + MRE532 + MRE518 + MRE517 + MRE516 + MRE574 + MRE576 + MRE545 + MRE544 + MRE477 + MRE541 + MRE578\n",
                "\n",
                "print(\"Your Total Credit Unit is:\",TCU2)\n",
                "\n",
                "#Calculate 2nd semester GPA\n",
                "GPA2=(PRE572_GP*PRE572) + (MRE502_GP*MRE502) + (MRE532_GP*MRE532) + (MRE518_GP*MRE518) + (MRE517_GP*MRE517) + (MRE516_GP*MRE516) + (MRE574_GP*MRE574) + (MRE576_GP*MRE576) + (MRE545_GP*MRE545) + (MRE544_GP*MRE544) + (MRE477_GP*MRE477) + (MRE541_GP*MRE541) + (MRE578_GP*MRE578)\n",
                "\n",
                "print(\"Your Total Grade Point is:\",GPA2)\n",
                "\n",
                "#Calculate the Total Grade Point Average of 2nd semester.\n",
                "TGPA10=GPA2/TCU2\n",
                "\n",
                "TGPA10=round(TGPA10,1)\n",
                "\n",
                "#Display Second Semester Grade Point Average\n",
                "print(\"Your 2nd Semester GPA is:\",TGPA10)\n",
                "\n",
                "#Calculate Cumulative Grade Point Avetage.\n",
                "CGPA=((TGPA1+TGPA2)/2 + (TGPA3+TGPA4)/2 + (TGPA5+TGPA6)/2 + (TGPA7+TGPA8)/2 + (TGPA9+TGPA10)/2) / 5\n",
                "\n",
                "#Round up to 1 decimal place\n",
                "CGPA=round(CGPA,1)\n",
                "\n",
                "#Diplay the Cumulative Grade Point Average\n",
                "print(\"Your CGPA is:\",CGPA)\n",
                "\n",
                "#Assign Class of Degree\n",
                "if((CGPA>=4.50) and (CGPA<=5.00)):\n",
                "    print(\"You have;\",\"FIRST CLASS\")\n",
                "elif((CGPA>=3.50) and (CGPA<=4.49)):\n",
                "    print(\"You have;\",\"SECOND CLASS UPPER\")\n",
                "elif((CGPA>=2.50) and (CGPA<=3.49)):\n",
                "    print(\"You have;\",\"SECOND CLASS LOWER\")\n",
                "elif((CGPA>=2.50) and (CGPA<=3.49)):\n",
                "    print(\"You have;\",\"THIRD CLASS\")\n",
                "elif((CGPA>=1.00) and (CGPA<=1.49)):\n",
                "    print(\"You have;\",\"PASS\")\n",
                "elif((CGPA>=0.00) and (CGPA<=0.99)):\n",
                "    print(\"You have;\",\"FAIL\")\n",
                "else:\n",
                "    print(\"Grade Unknown\")"
            ],
            "metadata": {
                "azdata_cell_guid": "d2798b71-7cc2-4486-846f-d22bd857c396",
                "language": "python"
            },
            "outputs": [
                {
                    "output_type": "stream",
                    "name": "stdout",
                    "text": "Welcome to the CGPA Calculator!\nCreated by Marine Engineering 200 Level Students University of Benin\nThis is a Program to calculate the CGPA of all Courses in 2 Semesters\nFor Grade points A=5, B=4, C=3, D=2, E=1, F=0\nPlease enter Grade Point ...PRE571:4\nPlease enter Grade Point ...MRE591:4\nPlease enter Grade Point ...MRE513:4\nPlease enter Grade Point ...MRE511:4\nPlease enter Grade Point ...MRE506:4\nPlease enter Grade Point ...MRE508:4\nPlease enter Grade Point ...MRE527:4\nPlease enter Grade Point ...MRE501:4\nPlease Input Credit Unit\nPlease enter Credit Unit ...PRE571:3\nPlease enter Credit Unit ...MRE591:3\nPlease enter Credit Unit ...MRE513:3\nPlease enter Credit Unit ...MRE511:3\nPlease enter Credit Unit ...MRE506:3\nPlease enter Credit Unit ...MRE508:3\nPlease enter Credit Unit ...MRE527:3\nPlease enter Credit Unit ...MRE501:3\nYour Total Credit Unit is: 24\nYour Total Grade Point is: 96\nYour 1st Semester GPA is: 4.0\nPlease enter Grade Points & Credit Units of 2nd Semester\nPlease enter Grade Point ...PRE572:5\nPlease enter Grade Point ...MRE502:5\npick 5 optonal courses and input 0 as grade point for courses you did not take\nPlease enter Grade Point ...MRE532:5\nPlease enter Grade Point ...MRE581:5\nPlease enter Grade Point ...MRE517:5\nPlease enter Grade Point ...MRE516:5\nPlease enter Grade Point ...MRE574:5\nPlease enter Grade Point ...MRE576:0\nPlease enter Grade Point ...MRE545:0\nPlease enter Grade Point ...MRE544:0\nPlease enter Grade Point ...MRE477:0\nPlease enter Grade Point ...MRE541:0\nPlease enter Grade Point ...MRE578:0\nPlease Input Credit Units\nPlease enter Credit Unit ...PRE572:3\nPlease enter Credit Unit ...MRE502:3\npick 5 optonal courses and input 0 as credit unit for courses you did not take\nPlease enter Credit Unit ...MRE532:3\nPlease enter Credit Unit ...MRE581:3\nPlease enter Credit Unit ...MRE517:3\nPlease enter Credit Unit ...MRE516:3\nPlease enter Credit Unit ...MRE574:3\nPlease enter Credit Unit ...MRE576:0\nPlease enter Credit Unit ...MRE545:0\nPlease enter Credit Unit ...MRE544:0\nPlease enter Credit Unit ...MRE477:0\nPlease enter Credit Unit ...MRE541:0\nPlease enter Credit Unit ...MRE578:0\nYour Total Credit Unit is: 21\nYour Total Grade Point is: 105\nYour 2nd Semester GPA is: 5.0\nYour CGPA is: 4.5\nYou have; FIRST CLASS\n"
                }
            ],
            "execution_count": 12
        },
        {
            "cell_type": "code",
            "source": [],
            "metadata": {
                "azdata_cell_guid": "f050a703-0f82-4e0f-afd4-70c493d7d899",
                "language": "python"
            },
            "outputs": [],
            "execution_count": null
        },
        {
            "cell_type": "code",
            "source": [],
            "metadata": {
                "azdata_cell_guid": "788eebf3-209d-436d-b9c8-91e783947920",
                "language": "python"
            },
            "outputs": [],
            "execution_count": null
        }
    ]
}